// ── Curated Idiom Database ────────────────────────────────────────────────────
// Single source of truth for all idioms used across start-round and validate.
//
// Rules:
//  • he / en must be genuine cultural equivalents — NOT literal translations.
//  • visualPrompt must be rich enough for Fal.ai to produce a solvable visual riddle.
//  • clues are the 3-4 key visual elements used in the image (for future hint system).
//  • difficulty: 1=easy  2=medium  3=hard

export interface IdiomEntry {
  he: string;
  en: string;
  visualPrompt: string;
  explanation: string;
  clues: string[];
  difficulty: 1 | 2 | 3;
}

export const IDIOMS: IdiomEntry[] = [
  {
    he: 'לשבור את הקרח',
    en: 'Break the ice',
    visualPrompt: 'A confident person dramatically shattering a towering wall of ice at a social gathering, warm golden light bursting through the cracks, nervous strangers on one side beginning to smile warmly on the other, blue frost meets amber warmth',
    explanation: 'To ease tension and start a conversation among strangers. Making the first move to overcome awkwardness.',
    clues: ['ice wall shattering', 'social gathering', 'strangers warming up', 'blue frost and warm light'],
    difficulty: 1,
  },
  {
    he: 'לחפש מחט בערימת שחת',
    en: 'A needle in a haystack',
    visualPrompt: 'A desperate person digging through an impossibly enormous haystack that fills an entire barn, a single tiny needle barely glinting somewhere deep inside, conveying a futile exhausting search',
    explanation: 'Searching for something extremely difficult or near-impossible to find. An overwhelming, fruitless task.',
    clues: ['enormous haystack', 'tiny glinting needle hidden inside', 'frantic desperate search', 'impossible task'],
    difficulty: 1,
  },
  {
    he: 'חתול בשק',
    en: 'A pig in a poke',
    visualPrompt: 'A burlap sack tied with rope at a marketplace stall, a cat\'s paw and one curious eye peeking through a small gap, a suspicious buyer examining it without opening it fully, mystery and uncertainty',
    explanation: 'Buying or accepting something without knowing what it really is. A hidden surprise or unknown deal.',
    clues: ['burlap sack at market', 'cat peeking out', 'uncertain purchase', 'hidden surprise inside'],
    difficulty: 2,
  },
  {
    he: 'פיל בחנות חרסינה',
    en: 'A bull in a china shop',
    visualPrompt: 'A large clumsy elephant standing inside a delicate porcelain shop surrounded by cracked and toppled figurines and teacups, a horrified shopkeeper watching helplessly, the elephant looking apologetic',
    explanation: 'A clumsy or tactless person in a delicate situation requiring great care and finesse.',
    clues: ['elephant in china shop', 'broken porcelain everywhere', 'delicate objects destroyed', 'horrified shopkeeper'],
    difficulty: 1,
  },
  {
    he: 'כלב נובח לא נושך',
    en: 'His bark is worse than his bite',
    visualPrompt: 'A cartoon dog with an enormous wide-open barking mouth and dramatic growling expression, but close-up reveals its teeth are made of soft rubber harmlessly bent, other animals looking completely unimpressed',
    explanation: 'Someone who makes loud threats or seems scary but is actually harmless and never follows through.',
    clues: ['cartoon barking dog', 'soft rubber teeth revealed', 'harmless despite loud noise', 'unimpressed onlookers'],
    difficulty: 1,
  },
  {
    he: 'לשפוך שמן על האש',
    en: 'Add fuel to the fire',
    visualPrompt: 'A person triumphantly pouring a huge oil barrel onto a roaring bonfire causing a massive flame explosion, alarmed people running away in every direction, situation clearly made catastrophically worse',
    explanation: 'Making a bad or tense situation dramatically worse instead of calming it down.',
    clues: ['oil barrel poured on huge fire', 'flames exploding larger', 'people fleeing in alarm', 'crisis worsening'],
    difficulty: 1,
  },
  {
    he: 'שתי ציפורים במכה אחת',
    en: 'Kill two birds with one stone',
    visualPrompt: 'A single small stone mid-flight simultaneously striking two cartoon birds, both with utterly surprised expressions, a satisfied person watching in the background having solved two problems with one elegant action',
    explanation: 'Accomplishing two goals with a single action. Maximum efficiency at its best.',
    clues: ['one stone', 'two birds struck simultaneously', 'efficient double solution', 'satisfied person watching'],
    difficulty: 1,
  },
  {
    he: 'היד על הדופק',
    en: 'Keep your finger on the pulse',
    visualPrompt: 'A focused person\'s index finger resting precisely on a wrist measuring a heartbeat, a glowing real-time information dashboard and live news ticker visible in the background, total alertness',
    explanation: 'Staying closely informed and constantly up-to-date about developments in a situation.',
    clues: ['finger resting on wrist pulse', 'heartbeat monitoring', 'live information dashboard', 'alert and informed'],
    difficulty: 2,
  },
  {
    he: 'לדפוק על הברזל בעוד חם',
    en: 'Strike while the iron is hot',
    visualPrompt: 'A blacksmith hammering a glowing orange-hot piece of iron on an anvil with dramatic sparks flying, intense urgency and momentum, a clock nearby showing the perfect fleeting moment to act',
    explanation: 'Take advantage of a favorable opportunity before it passes. Act decisively at exactly the right moment.',
    clues: ['blacksmith hammering hot iron', 'glowing orange metal', 'sparks flying dramatically', 'clock showing perfect timing'],
    difficulty: 1,
  },
  {
    he: 'בין הפטיש לסדן',
    en: 'Between a rock and a hard place',
    visualPrompt: 'A tiny frightened person trapped between a gigantic hammer descending from above and a massive immovable anvil below, pressing in from both sides simultaneously with absolutely no escape route visible',
    explanation: 'Caught between two equally difficult options with no good way out. A true impossible dilemma.',
    clues: ['person trapped between hammer and anvil', 'pressing in from both sides', 'no escape route visible', 'impossible dilemma'],
    difficulty: 2,
  },
  {
    he: 'ראש בענן',
    en: 'Head in the clouds',
    visualPrompt: 'A person standing firmly on the ground with their head literally inside a soft fluffy white cloud, dreamy unfocused eyes visible through the mist, completely unaware of the real world happening around them',
    explanation: 'A daydreamer who is disconnected from reality, lost in fantasy and not paying attention to what matters.',
    clues: ['head inside fluffy cloud', 'feet on ground', 'dreamy disconnected expression', 'unaware of surroundings'],
    difficulty: 1,
  },
  {
    he: 'כבש שחור',
    en: 'The black sheep',
    visualPrompt: 'A large flock of identical white fluffy sheep in a bright green meadow, one lone black sheep standing slightly apart from the group, different and isolated with a subtle quiet sadness',
    explanation: 'The odd one out in a group or family — someone very different who does not fit in with the others.',
    clues: ['one black sheep among white sheep', 'isolated from the flock', 'clearly different from group', 'standing apart in field'],
    difficulty: 1,
  },
  {
    he: 'אין ורד בלי קוצים',
    en: 'Every rose has its thorn',
    visualPrompt: 'An exquisitely beautiful blooming red rose in extreme close-up, surrounded by multiple vicious sharp thorns that are prominently featured, beauty and pain inseparably intertwined in perfect tension',
    explanation: 'Every good thing comes with difficulties or a downside. Beauty always comes with a price.',
    clues: ['beautiful red rose close-up', 'sharp thorns prominently featured', 'beauty and pain together', 'inseparable contrast'],
    difficulty: 1,
  },
  {
    he: 'עיניים גדולות מהבטן',
    en: 'Eyes bigger than your stomach',
    visualPrompt: 'A person with cartoonishly huge bulging eyes staring longingly at a tiny modest plate of food, their small stomach visibly unable to contain what their enormous eyes desire, overwhelmed greedy expression',
    explanation: 'Wanting or taking far more than you can actually handle or consume. Overreaching ambition.',
    clues: ['huge cartoon eyes', 'tiny plate of food', 'small visible stomach', 'wanting more than possible'],
    difficulty: 1,
  },
  {
    he: 'אין עשן בלי אש',
    en: 'Where there\'s smoke there\'s fire',
    visualPrompt: 'Large dramatic billowing smoke clouds rising into the sky, and deep at the very bottom barely visible a small actual fire burning, the smoke unmistakably revealing a hidden truth',
    explanation: 'If there are signs or rumors about something, there is usually a real cause behind them.',
    clues: ['huge smoke cloud', 'tiny hidden fire at bottom', 'smoke revealing hidden truth', 'dramatic sky'],
    difficulty: 2,
  },
  {
    he: 'מרגלית לפני חזיר',
    en: 'Cast pearls before swine',
    visualPrompt: 'A muddy pig sniffing at a pile of lustrous expensive pearls with complete indifference and disinterest, priceless treasure wasted on a totally unappreciative audience, muddy farm background',
    explanation: 'Giving something precious or valuable to someone who cannot appreciate it. Quality entirely wasted.',
    clues: ['pig ignoring pearls', 'precious pearls lying in mud', 'wasted on unappreciative animal', 'muddy farm background'],
    difficulty: 2,
  },
  {
    he: 'לבנות טירות באוויר',
    en: 'Build castles in the air',
    visualPrompt: 'A dreamy person joyfully constructing elaborate floating castles high among the clouds with their bare hands, beautiful impossible structures drifting with no foundation below, lost in pure fantasy',
    explanation: 'Making grand but unrealistic plans with no grounding in reality. Pure wishful thinking.',
    clues: ['floating castle among clouds', 'person building with bare hands', 'no foundation below', 'impossible fantasy structures'],
    difficulty: 1,
  },
  {
    he: 'דג גדול אוכל דג קטן',
    en: 'Big fish eat little fish',
    visualPrompt: 'An underwater scene showing a clear size hierarchy: an enormous fish swallowing a medium fish which is simultaneously swallowing a tiny fish, power and ruthlessness illustrated through shrinking sizes',
    explanation: 'The powerful exploit the weak. Might makes right in competitive situations.',
    clues: ['fish swallowing smaller fish', 'chain of decreasing sizes', 'underwater power hierarchy', 'biggest consuming smallest'],
    difficulty: 2,
  },
  {
    he: 'כל הנוצץ אינו זהב',
    en: 'All that glitters is not gold',
    visualPrompt: 'Shiny golden-looking objects being scratched or chipped to reveal cheap grey plastic and painted cardboard underneath, beautiful exterior concealing entirely worthless interior, deceptive appearance exposed',
    explanation: 'Things that look impressive or valuable may be worthless or fake underneath. Never judge by appearances.',
    clues: ['shiny objects scratched open', 'cheap material revealed inside', 'deceptive golden appearance', 'fool\'s gold exposed'],
    difficulty: 2,
  },
  {
    he: 'לשבת על הגדר',
    en: 'Sit on the fence',
    visualPrompt: 'A person sitting perfectly balanced on top of a wooden fence with one leg dangling on each side, looking left and right with equal indecision without committing to either direction',
    explanation: 'Refusing to take a side or make a decision. Staying neutral to avoid any commitment.',
    clues: ['person sitting on top of fence', 'one leg each side', 'looking both directions equally', 'refusing to choose'],
    difficulty: 1,
  },
  {
    he: 'יד אחת מרחיצה את השנייה',
    en: 'You scratch my back I\'ll scratch yours',
    visualPrompt: 'Two hands cooperatively washing each other under a flowing stream of water in a circular motion, perfect mutual give-and-take, symbiotic cooperation beautifully visualized',
    explanation: 'Mutual assistance and reciprocal favors. I help you and you help me in return.',
    clues: ['two hands washing each other', 'running water', 'circular cooperative motion', 'mutual assistance'],
    difficulty: 2,
  },
  {
    he: 'לקחת את השור בקרניים',
    en: 'Take the bull by the horns',
    visualPrompt: 'A brave determined person gripping a powerful bull directly by both its horns, eyes locked forward with total confidence, facing the challenge completely head-on without any hesitation',
    explanation: 'Confronting a difficult problem directly and boldly instead of avoiding it. Decisive courage.',
    clues: ['person gripping bull by both horns', 'direct brave confrontation', 'determined confident eyes', 'facing challenge head-on'],
    difficulty: 1,
  },
  {
    he: 'כשהחתול לא בבית העכברים רוקדים',
    en: 'When the cat\'s away the mice will play',
    visualPrompt: 'Mice throwing an energetic wild party in a kitchen complete with tiny balloons and confetti, an empty cat bed and a cat leash hanging unused by the door, authority conspicuously absent',
    explanation: 'People misbehave or relax the rules when the authority figure is not watching.',
    clues: ['mice partying in kitchen', 'empty cat bed visible', 'unused cat leash on door', 'wild celebration without supervision'],
    difficulty: 1,
  },
  {
    he: 'אחד ביד שווה שניים בשדה',
    en: 'A bird in hand is worth two in the bush',
    visualPrompt: 'One contented bird sitting safely in a person\'s cupped hand, while two birds fly freely and uncertainly away into a distant field, the stark contrast between certainty and risky possibility',
    explanation: 'It is better to have something certain now than to risk losing it chasing something bigger.',
    clues: ['one bird safely in hand', 'two birds flying away to field', 'certainty versus risk', 'holding versus chasing'],
    difficulty: 1,
  },
  {
    he: 'נפל לבור שחפר',
    en: 'Hoisted by his own petard',
    visualPrompt: 'A person who was enthusiastically digging a trap now tumbling helplessly into that exact same hole they created, their own shovel falling in after them, perfect ironic karma reversal',
    explanation: 'Falling victim to your own scheme or trap. Suffering the very consequences of your own harmful plans.',
    clues: ['person falling into self-dug hole', 'own trap turned against them', 'shovel falling in after', 'ironic karma reversal'],
    difficulty: 2,
  },
  {
    he: 'מהפח אל הפחת',
    en: 'Out of the frying pan into the fire',
    visualPrompt: 'A figure barely escaping one dangerous burning trap only to immediately plummet into a much larger and deeper pit directly below, the second catastrophe visibly far worse than the first',
    explanation: 'Escaping one bad situation only to land in an even worse one immediately after.',
    clues: ['escaping one trap', 'falling into much bigger trap below', 'second disaster far worse', 'chain of worsening misfortune'],
    difficulty: 2,
  },
  {
    he: 'מה שזרע יקצור',
    en: 'You reap what you sow',
    visualPrompt: 'A farmer surrounded by a painful harvest of thorns and thistles, holding the very same thorny seeds they chose to plant shown in a flashback bubble above their head, regretful consequences made visible',
    explanation: 'Your actions and choices come back to you as consequences. What you give is exactly what you get.',
    clues: ['farmer harvesting thorns', 'seed planting flashback above', 'consequences of past choices', 'regretful painful harvest'],
    difficulty: 1,
  },
  {
    he: 'כל כלב בא יומו',
    en: 'Every dog has its day',
    visualPrompt: 'A small underdog-looking scruffy dog standing triumphantly on a championship winner\'s podium holding a golden trophy, tail wagging joyfully, confetti raining down in a totally unexpected victory moment',
    explanation: 'Everyone eventually gets their moment of success or recognition, no matter how unlikely it seems.',
    clues: ['small scruffy dog on winner podium', 'holding golden trophy', 'confetti raining down', 'unexpected triumph moment'],
    difficulty: 1,
  },
  {
    he: 'שן תחת שן',
    en: 'An eye for an eye',
    visualPrompt: 'Two perfectly identical large teeth facing each other on a perfectly balanced justice scale, exactly equal weight on both sides, symmetrical retaliation measured with mathematical precision',
    explanation: 'Equal retaliation, giving back exactly what was done to you. Proportional justice, no more and no less.',
    clues: ['two teeth on balanced scale', 'perfect symmetry', 'equal retaliation measured', 'justice scale perfectly balanced'],
    difficulty: 2,
  },
  {
    he: 'לזרוק עפר בעיניים',
    en: 'Pull the wool over someone\'s eyes',
    visualPrompt: 'A cunning person throwing a dramatic handful of dust and dirt directly into another person\'s wide-open eyes, completely blinding and deceiving them, the victim entirely unable to see the truth',
    explanation: 'To deliberately deceive or mislead someone, clouding their judgment so they cannot see the truth.',
    clues: ['dust thrown at eyes', 'deliberate blinding deception', 'cunning deceiver throwing dirt', 'victim cannot see truth'],
    difficulty: 2,
  },
  {
    he: 'בא לגור ונהיה בעל הבית',
    en: 'Give an inch take a mile',
    visualPrompt: 'A guest arriving with a tiny suitcase being welcomed warmly, then shown later sitting in the host\'s armchair wearing their slippers and robe, having completely taken over the entire home',
    explanation: 'Taking much more than what was offered. A guest who gradually overstays and takes total control.',
    clues: ['guest arriving with tiny suitcase', 'gradually taking over home', 'sitting in host\'s armchair', 'wearing owner\'s slippers and robe'],
    difficulty: 2,
  },
  {
    he: 'ים של צרות',
    en: 'A sea of troubles',
    visualPrompt: 'A tiny fragile person on a small raft completely surrounded by a vast overwhelming stormy ocean, enormous labeled waves crashing in from all sides with different problems named on each wave',
    explanation: 'An overwhelming number of problems and difficulties hitting all at once. Being completely swamped by trouble.',
    clues: ['tiny person on raft', 'vast stormy overwhelming ocean', 'labeled waves of different problems', 'surrounded from all sides'],
    difficulty: 2,
  },
  {
    he: 'לדוג במים עכורים',
    en: 'Fish in troubled waters',
    visualPrompt: 'A sly-looking fisherman contentedly fishing in very dark turbulent murky water while others around look confused by the surrounding chaos, calmly taking advantage of disorder for personal gain',
    explanation: 'Taking personal advantage of chaos, confusion, or disorder. Profiting opportunistically from others\' misfortune.',
    clues: ['sly fisherman in murky water', 'dark turbulent chaotic water', 'others confused around them', 'calm opportunistic advantage'],
    difficulty: 2,
  },
  {
    he: 'כל עורב ולדו לבן',
    en: 'Love is blind',
    visualPrompt: 'A jet-black raven parent looking with overflowing adoration at its baby chick which appears to glow pure brilliant white and perfect through the parent\'s completely biased loving eyes, hearts floating around them',
    explanation: 'Parents always see their own children as perfect and special. Love distorts our perception of those we adore.',
    clues: ['black raven with glowing white chick', 'parental adoration bias', 'child appearing perfect to parent', 'hearts of love floating'],
    difficulty: 3,
  },
  {
    he: 'לשרוף גשרים',
    en: 'Burn your bridges',
    visualPrompt: 'A person walking confidently away from a wooden bridge they have just set ablaze behind them, the connection to their past completely destroyed in flames, no way to ever return, dramatic fire',
    explanation: 'Permanently destroying a relationship or option, making it absolutely impossible to go back.',
    clues: ['person walking away', 'bridge burning behind them', 'no return path possible', 'past connection destroyed by fire'],
    difficulty: 2,
  },
  {
    he: 'לא לגרות את הדוב',
    en: 'Let sleeping dogs lie',
    visualPrompt: 'A large bear sleeping peacefully in a sun-dappled forest clearing, a person tiptoeing very carefully and silently past it without making a sound, wisely choosing not to disturb the dangerous situation',
    explanation: 'Avoid stirring up old problems or dormant trouble. Leave well enough alone.',
    clues: ['sleeping bear in forest', 'person tiptoeing silently past', 'choosing not to disturb danger', 'wise careful avoidance'],
    difficulty: 2,
  },
  {
    he: 'עולה ביד ורגל',
    en: 'Cost an arm and a leg',
    visualPrompt: 'A price tag literally shaped like a human arm and leg attached to a luxury item in a store window, a shocked customer staring at the absurdly expensive cost with eyes wide and jaw dropped',
    explanation: 'Something outrageously expensive. Costing an extreme amount of money.',
    clues: ['arm and leg as price tag', 'luxury item in shop window', 'shocked customer jaw dropped', 'outrageously expensive cost'],
    difficulty: 1,
  },
  {
    he: 'משחק ילדים',
    en: 'A piece of cake',
    visualPrompt: 'Young children effortlessly and joyfully breezing through a task that a frustrated adult is struggling with impossibly, illustrating something ridiculously simple for the right person',
    explanation: 'Something extremely easy to do. Requires absolutely no effort at all.',
    clues: ['children doing task effortlessly', 'adult struggling with same task', 'effortless simplicity for some', 'ridiculously easy comparison'],
    difficulty: 2,
  },
  {
    he: 'לעשות הרים מגבעות',
    en: 'Make a mountain out of a molehill',
    visualPrompt: 'A tiny ant-sized molehill on the ground casting an enormous dramatic shadow shaped like a towering mountain range, a person reacting with complete hysteria to the minuscule bump',
    explanation: 'Greatly exaggerating a minor problem and treating it as if it were a major catastrophic crisis.',
    clues: ['tiny molehill casting huge mountain shadow', 'enormous shadow from small bump', 'person overreacting hysterically', 'exaggerated problem size'],
    difficulty: 2,
  },
  {
    he: 'לשחות נגד הזרם',
    en: 'Swim against the tide',
    visualPrompt: 'A single determined swimmer pushing powerfully upstream against a strong current, while all other swimmers around them flow easily and comfortably downstream with the flow, alone in determined opposition',
    explanation: 'Going against the majority opinion or convention. Standing alone in opposition to popular trends.',
    clues: ['swimmer going against current', 'others flowing downstream easily', 'lone determined opposition', 'upstream struggle against flow'],
    difficulty: 2,
  },
  {
    he: 'ביצה ותרנגולת',
    en: 'The chicken and the egg',
    visualPrompt: 'A chicken and a large egg standing face-to-face with equal enormous question marks hovering above both of them, an unsolvable circular loop, confused philosophers scratching their heads nearby',
    explanation: 'An unsolvable circular dilemma about which came first. An impossible question of origin.',
    clues: ['chicken and egg face to face', 'giant question marks above both', 'circular unsolvable dilemma', 'philosophers confused nearby'],
    difficulty: 1,
  },
  {
    he: 'ציפור אחת לא עושה קיץ',
    en: 'One swallow does not make a summer',
    visualPrompt: 'A single small bird arriving triumphantly in a still-grey wintry landscape with bare trees and patches of snow, declaring summer prematurely while clearly absolutely nothing else has changed',
    explanation: 'One positive sign or event does not mean the whole situation has permanently changed. Don\'t celebrate too early.',
    clues: ['single bird in wintry landscape', 'bare trees and snow remaining', 'premature celebration', 'one sign not enough evidence'],
    difficulty: 3,
  },
  {
    he: 'הצד השני של המטבע',
    en: 'The other side of the coin',
    visualPrompt: 'A large coin being dramatically flipped to reveal an entirely different contrasting scene on its reverse face, showing two opposing perspectives of the exact same situation',
    explanation: 'The opposite viewpoint or the other aspect of a situation. There are always two sides to every story.',
    clues: ['coin being dramatically flipped', 'different scene on each side', 'opposite perspective revealed', 'two-sided truth'],
    difficulty: 2,
  },
  {
    he: 'שיטת הגזר והמקל',
    en: 'The carrot and the stick',
    visualPrompt: 'A classic scene of a large orange carrot dangling enticingly from a stick directly in front of a donkey, illustrating the reward-punishment motivation system, the animal choosing to reach for the reward',
    explanation: 'A system combining reward and punishment to motivate behavior. Incentive and threat working together.',
    clues: ['carrot dangling from stick', 'donkey reaching for carrot', 'reward and punishment system', 'classic motivation setup'],
    difficulty: 1,
  },
  {
    he: 'לעמוד בנעלי מישהו',
    en: 'Walk a mile in someone\'s shoes',
    visualPrompt: 'A person standing in oversized shoes that clearly belong to someone else, experiencing a completely different perspective and worldview, understanding how life feels from inside another person\'s position',
    explanation: 'To truly understand someone else\'s situation by experiencing their perspective firsthand. Deep empathy.',
    clues: ['person in someone else\'s oversized shoes', 'different footwear perspective', 'experiencing another\'s viewpoint', 'empathy through shared experience'],
    difficulty: 2,
  },
  {
    he: 'מחוץ לכחול',
    en: 'Out of the blue',
    visualPrompt: 'A dramatic lightning bolt striking completely and shockingly from a perfectly clear cloudless blue sky, people below looking stunned and completely unprepared for the totally unexpected sudden event',
    explanation: 'Something happening completely unexpectedly with absolutely no warning or advance signs whatsoever.',
    clues: ['lightning from perfectly clear blue sky', 'no clouds anywhere visible', 'shocked unprepared people below', 'totally unexpected sudden event'],
    difficulty: 2,
  },
  {
    he: 'קוץ בצד',
    en: 'A thorn in your side',
    visualPrompt: 'A person trying to walk normally but visibly and constantly bothered by a persistent large thorn stuck in their side that follows them everywhere, unable to remove it, a permanent irritating companion',
    explanation: 'A persistent and constant source of irritation or annoyance that never goes away.',
    clues: ['thorn stuck in person\'s side', 'persistent constant irritation', 'unable to remove it', 'following them everywhere'],
    difficulty: 2,
  },
  {
    he: 'ספינה שוקעת',
    en: 'A sinking ship',
    visualPrompt: 'A large vessel dramatically tilting and sinking into dark water while panicking rats and crew members scramble desperately to abandon it in every direction, a doomed enterprise everyone is fleeing',
    explanation: 'A failing organization or situation that everyone is desperately trying to escape from. Inevitable doom.',
    clues: ['ship dramatically sinking', 'rats and crew abandoning it', 'everyone fleeing in panic', 'doomed inevitable failure'],
    difficulty: 2,
  },
  {
    he: 'לשים ביצים בסל אחד',
    en: 'Put all your eggs in one basket',
    visualPrompt: 'A person dangerously balancing all their eggs in a single fragile basket directly over a hard stone floor, while multiple sturdy empty baskets sit unused safely nearby, dangerous risky consolidation',
    explanation: 'Putting all your resources or hope into a single option. Dangerous over-concentration of risk.',
    clues: ['all eggs in one fragile basket', 'multiple empty baskets unused nearby', 'dangerous balancing over hard floor', 'risk of total loss'],
    difficulty: 1,
  },
  {
    he: 'לא כל יום פורים',
    en: 'Not every day is a holiday',
    visualPrompt: 'One single bright colorful festive celebration day glowing on a calendar, completely surrounded by many plain grey ordinary dull workdays, the special day precious and rare among the mundane',
    explanation: 'Special occasions are rare and should be cherished. You cannot expect every day to be joyful and festive.',
    clues: ['one festive glowing day on calendar', 'many grey ordinary days surrounding it', 'rare precious special occasion', 'contrast between festive and mundane'],
    difficulty: 2,
  },
  // ── Batch 2: entries 51 – 100 ───────────────────────────────────────────────
  {
    he: 'מים שקטים עמוקים',
    en: 'Still waters run deep',
    visualPrompt: 'A perfectly calm mirror-like lake with a serene surface, but underwater dramatic deep currents and hidden depths are visible below, tranquil appearance hiding enormous hidden power',
    explanation: 'A quiet, reserved person often has great depth, intelligence, or passion hidden beneath the surface.',
    clues: ['calm mirror surface', 'deep dark currents below', 'deceptive tranquility', 'hidden depths revealed'],
    difficulty: 2,
  },
  {
    he: 'להחזיק אצבעות',
    en: 'Keep your fingers crossed',
    visualPrompt: 'Two fingers tightly crossed in a superstitious gesture of hope, a person holding them up while anxiously watching an uncertain outcome, wishing for luck',
    explanation: 'Hoping and wishing for a good outcome. A gesture of superstitious hope.',
    clues: ['fingers tightly crossed', 'anxious hopeful expression', 'uncertain outcome being watched', 'superstitious luck gesture'],
    difficulty: 1,
  },
  {
    he: 'לפגוע בול',
    en: 'Hit the nail on the head',
    visualPrompt: 'A hammer striking a nail with perfect precision exactly in the dead center of its head, a satisfying bullseye hit, conveying absolute accuracy and correctness',
    explanation: 'To describe something exactly right. To identify the precise problem or solution.',
    clues: ['hammer striking nail perfectly centered', 'bullseye precision hit', 'satisfying direct accuracy', 'nail driven perfectly straight'],
    difficulty: 1,
  },
  {
    he: 'הכוס חצי מלאה',
    en: 'The glass is half full',
    visualPrompt: 'A glass filled exactly halfway with water, two people looking at it from opposite sides — one smiling optimistically, one frowning pessimistically, same glass two worldviews',
    explanation: 'Choosing to see the positive side of a situation. An optimistic outlook on life.',
    clues: ['glass exactly half filled', 'optimist and pessimist viewing same glass', 'same situation two perspectives', 'positive or negative interpretation'],
    difficulty: 1,
  },
  {
    he: 'ללכת מסביב לסביב',
    en: 'Beat around the bush',
    visualPrompt: 'A person walking in wide circles around a bush instead of going directly to it, taking the long scenic route to avoid the obvious direct path, a frustrated listener waiting nearby',
    explanation: 'Avoiding the main point by talking around it. Refusing to get to the subject directly.',
    clues: ['person circling bush avoiding it', 'indirect path instead of direct', 'going around the obvious route', 'frustrated listener waiting'],
    difficulty: 1,
  },
  {
    he: 'לפספס את הרכבת',
    en: 'Miss the boat',
    visualPrompt: 'A person running breathlessly toward a train whose doors are just closing, the train beginning to pull away, the last chance slipping away with perfect timing missed by seconds',
    explanation: 'Missing an important opportunity because you were too late or too slow to act.',
    clues: ['person running to closing train doors', 'train starting to leave', 'opportunity departing', 'just seconds too late'],
    difficulty: 1,
  },
  {
    he: 'לקבור את הגרזן',
    en: 'Bury the hatchet',
    visualPrompt: 'Two former enemies standing together solemnly burying an axe in the ground between them, both with relieved expressions, a handshake being offered, conflict officially ended',
    explanation: 'To end a conflict and make peace. To forgive past grievances and reconcile.',
    clues: ['two enemies burying axe together', 'peace gesture being made', 'reconciliation moment', 'conflict officially ended in ground'],
    difficulty: 2,
  },
  {
    he: 'להרים ידיים',
    en: 'Throw in the towel',
    visualPrompt: 'A boxer\'s trainer dramatically throwing a white towel into the ring to signal surrender and defeat, the boxer exhausted but the fight finally over, admitting it is finished',
    explanation: 'To give up and admit defeat. To stop fighting when the battle is clearly lost.',
    clues: ['white towel thrown into boxing ring', 'trainer surrendering for boxer', 'admitting defeat is over', 'fight concluded by surrender'],
    difficulty: 1,
  },
  {
    he: 'לפני הסערה',
    en: 'The calm before the storm',
    visualPrompt: 'An eerily beautiful and perfectly still landscape with golden light, while on the horizon enormous dark storm clouds are rapidly approaching, the deceptive peaceful quiet before catastrophe',
    explanation: 'An unusual quiet period that precedes a major crisis or chaotic event.',
    clues: ['eerily still golden landscape', 'dark storm clouds on horizon', 'beautiful deceptive peace', 'imminent catastrophe approaching'],
    difficulty: 1,
  },
  {
    he: 'לחצות את הקו',
    en: 'Cross the line',
    visualPrompt: 'A person boldly stepping over a clearly marked red line on the ground, going beyond an obvious boundary, a warning sign nearby they chose to ignore, the point of no return crossed',
    explanation: 'Going beyond acceptable limits. Doing something that violates boundaries or decency.',
    clues: ['person stepping over red line', 'clear boundary being violated', 'warning sign ignored', 'point of no return'],
    difficulty: 1,
  },
  {
    he: 'מה שעיניים לא רואות לב לא כואב',
    en: 'Out of sight out of mind',
    visualPrompt: 'An important object covered by a curtain, the person who owned it cheerfully going about their day completely forgetting it exists, what is hidden is forgotten',
    explanation: 'Things you cannot see are easily forgotten or stop causing worry.',
    clues: ['object hidden behind curtain', 'owner happily forgetting it', 'out of view out of concern', 'what is hidden is not missed'],
    difficulty: 2,
  },
  {
    he: 'מאחורי הקלעים',
    en: 'Behind the scenes',
    visualPrompt: 'A glamorous theater stage performance visible to the audience, but pulling back the curtain reveals a hectic busy world of crew, cables, props, and preparation invisible to viewers',
    explanation: 'The unseen work and activity that happens out of public view to make something succeed.',
    clues: ['theater curtain pulled back', 'busy backstage invisible to audience', 'real work hidden from view', 'stage crew working in secret'],
    difficulty: 2,
  },
  {
    he: 'כתוב על הקיר',
    en: 'The writing is on the wall',
    visualPrompt: 'Ominous glowing words appearing on a stone wall predicting doom, people reading them with growing dread, an unmistakable warning sign that cannot be ignored',
    explanation: 'Clear signs that something bad is about to happen. An obvious warning of impending disaster.',
    clues: ['glowing ominous writing on stone wall', 'people reading with dread', 'unmistakable warning sign', 'doom foretold clearly'],
    difficulty: 2,
  },
  {
    he: 'לאבד את הראש',
    en: 'Lose your head',
    visualPrompt: 'A person in a complete panic making wild irrational decisions, their cool rational thoughts visibly flying away, losing all composure in a chaotic frantic situation',
    explanation: 'To completely lose composure and act irrationally under stress or pressure.',
    clues: ['person in complete panic', 'rational thoughts flying away', 'losing all composure', 'frantic irrational behavior'],
    difficulty: 1,
  },
  {
    he: 'להיות מחוץ לתמונה',
    en: 'Out of the loop',
    visualPrompt: 'A group of people standing inside an information circle sharing news and updates, while one confused person stands alone completely outside the loop excluded, missing everything',
    explanation: 'Being excluded from information or communication that others share. Not being informed.',
    clues: ['group inside information circle', 'one person excluded outside loop', 'missing all communication', 'confused excluded outsider'],
    difficulty: 2,
  },
  {
    he: 'לשמור על ראש קר',
    en: 'Keep a level head',
    visualPrompt: 'A person with a block of ice calmly balanced on their head remaining perfectly composed while chaos and fire erupts dramatically all around them, cool reason amid hot crisis',
    explanation: 'Remaining calm, rational, and clear-thinking in a difficult or stressful situation.',
    clues: ['ice on head keeping cool', 'chaos erupting all around', 'calm composed expression', 'rational amid crisis and fire'],
    difficulty: 2,
  },
  {
    he: 'להוציא מהכלים',
    en: 'Drive someone up the wall',
    visualPrompt: 'A person so intensely frustrated and maddened by irritation that they are literally climbing up a wall, fingernails scraping the plaster, driven to absolute exasperation',
    explanation: 'To irritate or frustrate someone to the point of madness.',
    clues: ['person literally climbing up a wall', 'extreme maddening frustration', 'driven to absolute exasperation', 'fingernails scraping in annoyance'],
    difficulty: 2,
  },
  {
    he: 'לסגור חשבונות',
    en: 'Settle old scores',
    visualPrompt: 'An old ledger book of past wrongs and debts finally being marked paid and closed forever, a person with a look of grim satisfaction finally achieving their long-delayed reckoning',
    explanation: 'Getting revenge or justice for past wrongs. Finally resolving old grievances.',
    clues: ['old ledger of wrongs being closed', 'past debts finally settled', 'grim satisfaction expression', 'long-delayed reckoning achieved'],
    difficulty: 2,
  },
  {
    he: 'שקר לבן',
    en: 'A white lie',
    visualPrompt: 'A small harmless-looking white lie floating gently like a white feather, told to spare someone\'s feelings, the kind intent visible, a gentle deception wrapped in good intentions',
    explanation: 'A small harmless lie told to protect someone\'s feelings or avoid minor trouble.',
    clues: ['small white floating lie', 'kind gentle intention', 'harmless deception', 'white feather of falsehood'],
    difficulty: 1,
  },
  {
    he: 'ימות השגרה',
    en: 'The daily grind',
    visualPrompt: 'A person on an endless hamster wheel running the same routine every single day, same coffee, same commute, same desk, endless repetitive cycle of ordinary life, monotony personified',
    explanation: 'The exhausting monotony of daily routine and repetitive work. The tiresome repetition of everyday life.',
    clues: ['person on endless hamster wheel', 'same routine every day', 'repetitive cycle of ordinary life', 'monotony grinding endlessly'],
    difficulty: 2,
  },
  {
    he: 'לאחוז בחבל משני קצותיו',
    en: 'Burn the candle at both ends',
    visualPrompt: 'A candle burning simultaneously from both its top and bottom ends at once, rapidly consuming itself in twice the time, a person exhausted from overwork visible nearby',
    explanation: 'Working excessively hard, staying up too late and rising too early. Depleting yourself from both ends.',
    clues: ['candle burning from both ends', 'rapidly consuming itself', 'double the rate of burning', 'exhausted person nearby'],
    difficulty: 2,
  },
  {
    he: 'לראות את היער מבעד לעצים',
    en: 'Can\'t see the forest for the trees',
    visualPrompt: 'A person with their face pressed right up against a single tree trunk, unable to see the enormous forest stretching behind them, missing the entire big picture by focusing on one detail',
    explanation: 'Being so focused on individual details that you miss the overall situation or bigger picture.',
    clues: ['face pressed against single tree', 'entire forest invisible behind them', 'missing big picture', 'detail obsession blocking overview'],
    difficulty: 2,
  },
  {
    he: 'לקפוץ מעל לפופיק',
    en: 'Bite off more than you can chew',
    visualPrompt: 'A person attempting to fit an impossibly enormous task through a tiny opening, clearly too ambitious for their capacity, biting into a huge item far bigger than their mouth can handle',
    explanation: 'Taking on more responsibility or work than you can possibly handle. Overreaching your capacity.',
    clues: ['enormous task through tiny opening', 'mouth biting oversized impossible piece', 'capacity completely overwhelmed', 'ambition far exceeding ability'],
    difficulty: 2,
  },
  {
    he: 'לפלס דרך',
    en: 'Pave the way',
    visualPrompt: 'A pioneer laying down a smooth road through untamed wilderness, making the path easier for those who will follow behind, building the foundation for future progress',
    explanation: 'Preparing the conditions that make something possible for others. Creating the path forward.',
    clues: ['pioneer building road through wilderness', 'path being cleared for others', 'future progress being enabled', 'foundation laid for those behind'],
    difficulty: 2,
  },
  {
    he: 'כנגד כל הסיכויים',
    en: 'Against all odds',
    visualPrompt: 'A tiny underdog figure achieving a stunning impossible victory against enormous overwhelming obstacles that tower over them, the improbable becoming reality through sheer will',
    explanation: 'Succeeding despite the chances of success being extremely low. Defying probability.',
    clues: ['tiny underdog vs enormous obstacles', 'impossible victory achieved', 'overwhelming odds beaten', 'improbable triumph through willpower'],
    difficulty: 1,
  },
  {
    he: 'ליפול על החרב',
    en: 'Fall on your sword',
    visualPrompt: 'A noble warrior honorably falling on their own sword, taking full personal blame and responsibility for a failure to protect others, sacrificing themselves with dignity',
    explanation: 'Accepting full blame and consequences for something, often to protect others. Noble self-sacrifice.',
    clues: ['warrior falling on their own sword', 'accepting full blame nobly', 'protecting others through self-sacrifice', 'taking responsibility with dignity'],
    difficulty: 3,
  },
  {
    he: 'לצאת בשן ועין',
    en: 'By the skin of your teeth',
    visualPrompt: 'A person escaping danger by the absolute most razor-thin margin possible, the gap between them and catastrophe measured in millimeters, a near-miraculous narrow escape',
    explanation: 'Barely managing to escape or succeed by the narrowest possible margin.',
    clues: ['narrowest possible escape margin', 'razor-thin gap from disaster', 'near-miraculous survival', 'millimeters between success and failure'],
    difficulty: 2,
  },
  {
    he: 'להמר על הסוס הנכון',
    en: 'Back the right horse',
    visualPrompt: 'A person confidently placing their bet on the correct winning horse at a racetrack while other horses lag behind, the smart choice paying off exactly as predicted',
    explanation: 'Choosing to support the person or option that turns out to be successful.',
    clues: ['betting on winning horse', 'smart prediction paying off', 'correct choice at racetrack', 'winner pulling ahead as chosen'],
    difficulty: 2,
  },
  {
    he: 'לשים את הדברים על השולחן',
    en: 'Put your cards on the table',
    visualPrompt: 'A person laying all their playing cards face-up on the table with total transparency, revealing everything they have with complete honesty, no secrets remaining hidden',
    explanation: 'Being completely open and honest. Revealing everything without hiding anything.',
    clues: ['all cards laid face-up on table', 'complete transparency shown', 'everything revealed honestly', 'no hidden information remaining'],
    difficulty: 2,
  },
  {
    he: 'לאכול אותה',
    en: 'Eat your words',
    visualPrompt: 'A person being forced to literally eat the proud words they previously spoke, swallowing their statements as they proved embarrassingly wrong, the words becoming food',
    explanation: 'Being forced to retract something you said confidently because it proved wrong.',
    clues: ['person eating their own spoken words', 'swallowing previous statements', 'proud claims being retracted', 'words becoming embarrassing food'],
    difficulty: 2,
  },
  {
    he: 'גבוה על סוס',
    en: 'Get off your high horse',
    visualPrompt: 'A person sitting atop an impossibly tall haughty horse, looking down their nose at everyone far below with extreme condescension and arrogance, everyone urging them to come down',
    explanation: 'Being arrogant and superior in attitude. Acting as if you are better than everyone else.',
    clues: ['person on impossibly tall horse', 'looking down at everyone condescendingly', 'extreme arrogance and superiority', 'others urging them down'],
    difficulty: 1,
  },
  {
    he: 'לדפוק ראש בקיר',
    en: 'Bang your head against the wall',
    visualPrompt: 'A frustrated person repeatedly banging their head against an immovable solid wall that refuses to budge, futile effort going nowhere, same result every time despite trying',
    explanation: 'Repeating a futile effort that will never succeed no matter how hard you try.',
    clues: ['person banging head against wall', 'wall completely immovable', 'futile repeated effort', 'same failed result every attempt'],
    difficulty: 1,
  },
  {
    he: 'לזרוק כפפה',
    en: 'Throw down the gauntlet',
    visualPrompt: 'A glove thrown dramatically to the ground between two rivals, a bold challenge being issued, the dramatic gesture of formal declaration of competition or conflict',
    explanation: 'Issuing a bold challenge or provocation. Formally declaring competition or confrontation.',
    clues: ['glove thrown to ground dramatically', 'formal challenge being issued', 'rivals facing confrontation', 'bold declaration of contest'],
    difficulty: 3,
  },
  {
    he: 'לחיות מהיד לפה',
    en: 'Live from hand to mouth',
    visualPrompt: 'A person\'s hand barely reaching their mouth with just enough minimal food each day, no savings or safety net anywhere visible, surviving on exactly the bare minimum daily',
    explanation: 'Having only just enough money to survive day-to-day with nothing left over to save.',
    clues: ['hand barely reaching mouth with food', 'no savings or safety net', 'just enough for today', 'precarious survival existence'],
    difficulty: 2,
  },
  {
    he: 'להניף דגל לבן',
    en: 'Wave the white flag',
    visualPrompt: 'A white flag being waved from behind a fortification as a signal of surrender and defeat, the fighting finally over, peace being accepted after the battle is lost',
    explanation: 'Admitting defeat and surrendering. Giving up the fight and asking for peace.',
    clues: ['white flag waved in surrender', 'battle finally over', 'defeat gracefully accepted', 'peace signal after conflict'],
    difficulty: 1,
  },
  {
    he: 'להיות על הגל',
    en: 'Ride the wave',
    visualPrompt: 'A surfer confidently riding a perfect powerful wave at its absolute peak, carried forward by unstoppable momentum, being at the crest of success and current trends',
    explanation: 'Being at the peak of a successful trend or period of success. Going along with powerful momentum.',
    clues: ['surfer on perfect powerful wave', 'at absolute peak of success', 'unstoppable momentum forward', 'riding the crest of a trend'],
    difficulty: 2,
  },
  {
    he: 'מהפכה בכוס מים',
    en: 'Tempest in a teapot',
    visualPrompt: 'A violent miniature hurricane and thunderstorm raging dramatically inside a tiny delicate teacup, enormous overreaction completely contained in a trivially small vessel',
    explanation: 'Making a huge fuss about something completely trivial and unimportant.',
    clues: ['hurricane inside tiny teacup', 'enormous storm in miniature vessel', 'massive overreaction to tiny problem', 'tempest contained in teapot'],
    difficulty: 2,
  },
  {
    he: 'להרוג את הזמן',
    en: 'Kill time',
    visualPrompt: 'A bored person idly stabbing at a clock or drowning the hours in pointless activities, waiting for something real to happen while slowly murdering their idle hours',
    explanation: 'Filling idle time with meaningless activities while waiting for something to happen.',
    clues: ['person stabbing at clock bored', 'killing idle waiting hours', 'pointless activities to fill time', 'bored waiting for something real'],
    difficulty: 1,
  },
  {
    he: 'תפוח נופל לא רחוק מהעץ',
    en: 'The apple doesn\'t fall far from the tree',
    visualPrompt: 'A red apple falling from a tree and landing mere centimeters from the trunk, a parent tree and child sapling side by side visibly identical, hereditary traits perfectly illustrated',
    explanation: 'Children closely resemble their parents in personality and behavior. Family traits are inherited.',
    clues: ['apple fallen close to tree trunk', 'parent and child tree side by side', 'very short distance from origin', 'inherited family resemblance'],
    difficulty: 1,
  },
  {
    he: 'כמו שני טיפות מים',
    en: 'Like two peas in a pod',
    visualPrompt: 'Two water droplets of absolutely identical shape and size sitting side by side, perfect mirror twins, indistinguishably similar, what defines one defines the other completely',
    explanation: 'Two people who are remarkably similar in appearance, personality, or behavior.',
    clues: ['two identical water droplets', 'perfect mirror-image twins', 'indistinguishably similar', 'one defines the other completely'],
    difficulty: 1,
  },
  {
    he: 'לחיות בבועה',
    en: 'Live in a bubble',
    visualPrompt: 'A person living comfortably and obliviously inside a beautiful transparent soap bubble, the harsh real world visible all around outside the bubble they cannot see, sheltered and isolated',
    explanation: 'Being isolated from reality, living in a protected world that does not reflect how things actually are.',
    clues: ['person inside transparent soap bubble', 'real world visible outside', 'isolated from reality', 'protective bubble about to pop'],
    difficulty: 2,
  },
  {
    he: 'להניח את הנשק',
    en: 'Lay down your arms',
    visualPrompt: 'A warrior carefully and deliberately placing their weapons on the ground, choosing peace over battle, a decisive moment of choosing to end the conflict voluntarily',
    explanation: 'Choosing to end a conflict and make peace. Voluntarily stopping the fight.',
    clues: ['warrior placing weapons on ground', 'deliberate choice for peace', 'conflict ended voluntarily', 'arms laid down in surrender'],
    difficulty: 2,
  },
  {
    he: 'לרדוף אחרי שני ארנבות',
    en: 'Chase two rabbits, catch neither',
    visualPrompt: 'A person running desperately in two directions simultaneously after two rabbits fleeing in exactly opposite ways, arms stretched both ways, catching absolutely neither one',
    explanation: 'Trying to achieve two incompatible goals at once leads to achieving nothing.',
    clues: ['person running two directions at once', 'two rabbits fleeing opposite ways', 'arms stretched impossibly apart', 'catching neither one'],
    difficulty: 2,
  },
  {
    he: 'טוב שם משמן טוב',
    en: 'A good name is better than riches',
    visualPrompt: 'A glowing respected reputation shining like gold on one side of a scale, outweighing a pile of actual gold coins on the other side, integrity worth visibly more than wealth',
    explanation: 'A good reputation and character are more valuable than money or possessions.',
    clues: ['reputation outweighing gold on scale', 'integrity heavier than wealth', 'good character vs money', 'honor glowing brighter than coins'],
    difficulty: 3,
  },
  {
    he: 'להגיע אחרי המלחמה',
    en: 'A day late and a dollar short',
    visualPrompt: 'A person arriving breathlessly to an empty silent battlefield long after the war has completely ended, everyone gone, relevant only when it no longer matters at all',
    explanation: 'Arriving too late with too little. Being irrelevant because the moment has already passed.',
    clues: ['arriving at empty ended battlefield', 'war completely over long ago', 'everyone already gone', 'too late to matter'],
    difficulty: 3,
  },
  {
    he: 'לשים ראש בחול',
    en: 'Bury your head in the sand',
    visualPrompt: 'An ostrich burying its head dramatically deep into the sand while obvious dangers approach from all sides, refusing to see what is clearly happening all around',
    explanation: 'Deliberately ignoring a problem hoping it will disappear. Refusing to face reality.',
    clues: ['ostrich head buried in sand', 'dangers approaching all sides', 'deliberate ignorance of problem', 'refusing to see obvious reality'],
    difficulty: 1,
  },
  {
    he: 'לקחת את עצמי בידיים',
    en: 'Pull yourself together',
    visualPrompt: 'A person literally gathering and reassembling scattered pieces of themselves after falling apart, recollecting composure, self-discipline winning over chaos',
    explanation: 'Regaining composure and self-control after a difficult emotional moment. Taking command of yourself.',
    clues: ['person reassembling scattered pieces', 'regaining composure from chaos', 'self-discipline winning', 'taking control of oneself'],
    difficulty: 2,
  },
  {
    he: 'לשים את הלב על כף היד',
    en: 'Wear your heart on your sleeve',
    visualPrompt: 'A glowing heart pinned visibly and prominently on the sleeve of someone\'s clothing, emotions completely exposed for all to see, feelings obvious to everyone around them',
    explanation: 'Showing your emotions openly and honestly without hiding them. Being emotionally transparent.',
    clues: ['glowing heart on clothing sleeve', 'emotions completely exposed', 'feelings visible to everyone', 'no emotional hiding at all'],
    difficulty: 2,
  },
  {
    he: 'לקרוא בין השורות',
    en: 'Read between the lines',
    visualPrompt: 'A person peering intently at the blank spaces between text lines on a page where a hidden message glows and appears, understanding the unstated meaning beyond literal words',
    explanation: 'Understanding the hidden or implied meaning that is not directly stated.',
    clues: ['person reading blank space between text lines', 'hidden glowing message appearing', 'meaning beyond literal words', 'subtext revealed in gaps'],
    difficulty: 2,
  },
  {
    he: 'לשפוך את לבו',
    en: 'Pour your heart out',
    visualPrompt: 'A person tilting and pouring their glowing heart like a vessel, emotional contents flowing out completely and honestly, total vulnerability and openness in one moment',
    explanation: 'Sharing your deepest feelings and emotions completely and openly.',
    clues: ['person pouring glowing heart like vessel', 'emotional contents flowing out', 'total emotional openness', 'deep feelings completely revealed'],
    difficulty: 2,
  },
];

// ── Lookup helpers ────────────────────────────────────────────────────────────

/** Find an idiom by its Hebrew text (exact match). */
export function findIdiomByHe(he: string): IdiomEntry | undefined {
  return IDIOMS.find(i => i.he === he);
}

/** Pick a random idiom from the full database. */
export function pickRandom(): IdiomEntry {
  return IDIOMS[Math.floor(Math.random() * IDIOMS.length)];
}
